const SU='https://mnwsijiqizyxzjinlhel.supabase.co',SK='sb_publishable_p9UUscQvUXs7lNj5qrmr2A_pTNOrBwz',TS='nutt-preview-8e71c9';
const MODELS=['gemini-3.5-flash-lite','gemini-3.1-flash-lite','gemini-3.6-flash'];
const TRUST=['seedfinder.eu','leafly.com','weedmaps.com','allbud.com','wikileaf.com','growdiaries.com','rollitup.org','icmag.com','thcfarmer.com','strainly.io','reddit.com','instagram.com','seedsman.com','northatlanticseed.com','multiversebeans.com','neptuneseedbank.com','deeplyrootedseedbank.com','greatlakesgenetics.com','jbcseeds.com','speakeasyseedbank.com','heritageseedbank.com','attitudeseedbank.co.uk','theclonefoundry.com','propercannabis.com'];
const BAD=['wikipedia.org','nasa.gov','imdb.com','rottentomatoes.com','britannica.com','merriam-webster.com','dictionary.com','space.com'];
const CAN=/\b(cannabis|marijuana|weed|strain|cultivar|genetic|genetics|breeder|bred|lineage|cross|hybrid|indica|sativa|terpene|flower|bud|clone|seed|phenotype|pheno|grow|cultivation|thc|cbd|kush|haze|diesel|cookies|gelato|runtz|sherb|zkittlez|chem|gmo|og)\b/i;
function txt(v=''){return String(v).replace(/```(?:json)?/gi,'').replace(/```/g,'').trim()}
function json(t){t=txt(t);try{return JSON.parse(t)}catch{}let a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(t.slice(a,b+1));throw Error('Research could not be structured.')}
async function ft(u,o={},ms=9000){let c=new AbortController(),id=setTimeout(()=>c.abort(),ms);try{return await fetch(u,{...o,signal:c.signal})}finally{clearTimeout(id)}}
async function user(h){let t=String(h||'').replace(/^Bearer\s+/i,'').trim();if(!t)return null;let r=await ft(`${SU}/auth/v1/user`,{headers:{apikey:SK,Authorization:`Bearer ${t}`}},7000).catch(()=>null);return r?.ok?r.json().catch(()=>null):null}
function dec(s=''){return String(s).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function strip(s=''){return dec(String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function host(u=''){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return''}}
function dm(h,l){return l.some(d=>h===d||h.endsWith('.'+d))}
function norm(s=''){return String(s).toLowerCase().replace(/[^a-z0-9#]+/g,' ').trim()}
function rss(x=''){return(x.match(/<item>[\s\S]*?<\/item>/gi)||[]).map(i=>{let g=t=>{let m=i.match(new RegExp(`<${t}>([\\s\\S]*?)<\\/${t}>`,'i'));return m?strip(m[1]):''};return{title:g('title'),url:g('link'),snippet:g('description')}}).filter(x=>x.title&&x.url)}
async function search(q){let r=await ft(`https://www.bing.com/search?format=rss&count=15&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0 (compatible; TheNuttBank/4.0)'}},7500).catch(()=>null);return r?.ok?rss(await r.text()):[]}
function score(r,name){let h=host(r.url);if(!h||dm(h,BAD))return-99;let t=`${r.title} ${r.snippet} ${r.url}`,z=norm(t),n=norm(name),b=norm(name.replace(/\s+#?\d+\s*$/,'')),tok=b.split(/\s+/).filter(x=>x.length>2),s=0;if(n&&z.includes(n))s+=12;else if(b&&z.includes(b))s+=9;s+=tok.filter(x=>z.includes(x)).length*2;if(CAN.test(t))s+=8;if(dm(h,TRUST))s+=8;if(/\/(strain|strains|genetics|cultivar|flower|product|seeds?|clones?)\b/i.test(r.url))s+=3;if(/bred by|lineage|cross(?:ed|ing)?|genetics/i.test(t))s+=3;if(!CAN.test(t)&&!dm(h,TRUST))s-=15;return s}
function uniq(a,key=x=>x.url){let s=new Set;return a.filter(x=>{let k=key(x);if(s.has(k))return false;s.add(k);return true})}
async function evidence(name,hints=''){let base=name.replace(/\s+#?\d+\s*$/,'').trim()||name,qs=[`"${name}" cannabis strain breeder lineage`,`"${name}" weed strain genetics history`,`"${name}" cultivation phenotype`, `"${base}" cannabis cultivar`, `site:seedfinder.eu "${base}"`, `site:leafly.com "${base}" strain`, `site:weedmaps.com "${base}" strain`, `site:reddit.com "${base}" strain grow`,hints&&`"${name}" cannabis ${hints}`].filter(Boolean),all=[];for(let i=0;i<qs.length;i+=2){all.push(...(await Promise.all(qs.slice(i,i+2).map(search))).flat());let good=uniq(all).map(x=>({...x,_s:score(x,name)})).filter(x=>x._s>=7);if(good.length>=10)break}let ranked=uniq(all).map(x=>({...x,_s:score(x,name)})).filter(x=>x._s>=7).sort((a,b)=>b._s-a._s).slice(0,12);if(!ranked.length)throw Error(`No strain profile was found for ${name}.`);let detailed=await Promise.all(ranked.slice(0,8).map(page));return[...detailed,...ranked.slice(8)]}
function at(tag,names){for(let n of names){let m=tag.match(new RegExp(`\\b${n}\\s*=\\s*["']([^"']+)["']`,'i'));if(m)return dec(m[1]).trim()}return''}
function abs(u,b){try{return u?new URL(dec(u),b).toString():''}catch{return''}}
async function page(r){let p=await ft(r.url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; TheNuttBank/4.0)'}},6500).catch(()=>null);if(!p?.ok||!(p.headers.get('content-type')||'').includes('text/html'))return r;let u=p.url||r.url,html=(await p.text()).slice(0,600000),body=strip(html),sent=body.split(/(?<=[.!?])\s+/).filter(s=>s.length>30&&s.length<500&&(CAN.test(s)||/bred by|lineage|cross(?:ed|ing)?|genetics/i.test(s))).slice(0,12).join(' '),imgs=[];let add=(raw,alt='',origin='page')=>{let image_url=abs(raw,u);if(image_url&&!image_url.startsWith('data:')&&!/\.svg(?:\?|$)/i.test(image_url))imgs.push({image_url,source_url:u,publisher:host(u),title:r.title,alt,origin})};for(let re of[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/ig,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/ig,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)["']/ig]){let m;while((m=re.exec(html)))add(m[1],'','meta')}for(let tag of(html.match(/<img\b[^>]*>/ig)||[]).slice(0,120)){let src=at(tag,['data-src','data-lazy-src','data-original','src']);if(!src){let ss=at(tag,['data-srcset','srcset']);src=ss?ss.split(',')[0].trim().split(/\s+/)[0]:''}add(src,at(tag,['alt']),'page')}return{...r,url:u,publisher:host(u),page_text:sent,images:uniq(imgs,x=>x.image_url).slice(0,8)}}
const REJECT=/\b(logo|logotype|icon|avatar|favicon|banner|badge|placeholder|graphic|artwork|illustration|packaging|package|label|sticker|merch|shirt|hoodie|poster|flyer|menu|brandmark|screenshot|profile)\b/i,FLOW=/\b(cannabis|marijuana|flower|bud|buds|nug|nugs|cola|plant|cultivar|strain|trichome|macro|harvest)\b/i;
function iscore(im,name){let t=`${im.alt||''} ${im.title||''} ${im.image_url||''}`;if(REJECT.test(t))return-99;let z=norm(t),b=norm(name.replace(/\s+#?\d+\s*$/,'')),s=b&&z.includes(b)?10:0;s+=b.split(/\s+/).filter(x=>x.length>2&&z.includes(x)).length*2;if(FLOW.test(t))s+=6;if(im.origin==='page')s+=2;return s}
async function dl(im){let r=await ft(im.image_url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0','Accept':'image/webp,image/png,image/jpeg,*/*;q=.5'}},8000).catch(()=>null);if(!r?.ok)return null;let mime=(r.headers.get('content-type')||'').split(';')[0];if(!['image/jpeg','image/png','image/webp'].includes(mime))return null;let b=Buffer.from(await r.arrayBuffer());if(!b.length||b.length>1800000)return null;return{...im,mime,data:b.toString('base64')}}
async function model(parts,max=5000,ms=45000){let key=process.env.GEMINI_API_KEY;if(!key)throw Error('GEMINI_API_KEY is missing.');let last='';for(let m of MODELS){let r=await ft(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent`,{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{maxOutputTokens:max,responseMimeType:'application/json'}})},ms).catch(()=>null);if(!r){last='timeout';continue}if(!r.ok){last=(await r.text()).slice(0,250);continue}let d=await r.json(),text=(d?.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('').trim();if(text)return{text,model:m};last='empty'}throw Error(`Research synthesis failed: ${last}`)}
function prompt(name,h,e,ims){let src=e.map((x,i)=>`[${i+1}] ${x.title}\nPublisher: ${x.publisher||host(x.url)}\nURL: ${x.url}\nSearch excerpt: ${x.snippet||''}\nPage evidence: ${x.page_text||''}`).join('\n\n');return`Create a concise Google-style cannabis cultivar reference profile for "${name}" from ONLY the evidence below. Do not repeat facts. Core lineage/history should favor breeders, SeedFinder, Leafly, Weedmaps and established cannabis sources. Reddit/forums are for sentiment and grow reports. Clearly label conflicts. Commonly reported uses are user reports, not medical facts.${h?` Owner hint: ${h}`:''}\n\n${src}\n\nYou are also given ${ims.length} candidate images. Accept an image only when it visibly shows real cannabis flower/buds/nugs/colas or a live cannabis plant. Reject logos, promo art, text graphics, packaging, labels, menus, screenshots, people, jars, and branded graphics.\nReturn ONLY JSON with: canonical_name, aliases[], overview, breeder_or_creator, exact_cross, expanded_lineage, type, potency, history, aroma[], flavor[], appearance, commonly_reported_effects[], commonly_reported_uses[], cultivation{flowering_time,yield,difficulty,growth_structure,environment,notes[]}, notable_cuts_or_phenotypes[], community_sentiment{summary,positive_themes[],cautions[],platform_notes[]}, conflicting_claims[], source_or_cut, provenance, parent_background[], related_cultivars[], aroma_and_flavor[], cultivation_notes, research_summary, confidence(high|medium|low), image_results:[{index:number,classification:"cannabis_flower"|"cannabis_live_plant"|"reject",confidence:number}].`}
function A(v){return Array.isArray(v)?v.filter(Boolean).map(String):[]}function O(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function profile(raw,name,sources,images){let c=O(raw.cultivation),s=O(raw.community_sentiment),a=A(raw.aroma),f=A(raw.flavor),mix=A(raw.aroma_and_flavor).length?A(raw.aroma_and_flavor):[...a,...f],u=x=>[...new Set(x.filter(Boolean))];return{canonical_name:raw.canonical_name||name,aliases:A(raw.aliases),overview:raw.overview||'',breeder_or_creator:raw.breeder_or_creator||'Not confirmed',exact_cross:raw.exact_cross||'Not confirmed',expanded_lineage:raw.expanded_lineage||raw.exact_cross||'Not confirmed',type:raw.type||'Not consistently reported',potency:raw.potency||'Not consistently reported',history:raw.history||'',aroma:a,flavor:f,appearance:raw.appearance||'',commonly_reported_effects:A(raw.commonly_reported_effects),commonly_reported_uses:A(raw.commonly_reported_uses),cultivation:{flowering_time:c.flowering_time||'',yield:c.yield||'',difficulty:c.difficulty||'',growth_structure:c.growth_structure||'',environment:c.environment||'',notes:A(c.notes)},notable_cuts_or_phenotypes:A(raw.notable_cuts_or_phenotypes),community_sentiment:{summary:s.summary||'',positive_themes:A(s.positive_themes),cautions:A(s.cautions),platform_notes:A(s.platform_notes)},conflicting_claims:A(raw.conflicting_claims),source_or_cut:raw.source_or_cut||'',provenance:raw.provenance||`Synthesized from ${sources.length} cannabis sources.`,parent_background:A(raw.parent_background),related_cultivars:A(raw.related_cultivars),aroma_and_flavor:u(mix),cultivation_notes:raw.cultivation_notes||A(c.notes).join(' '),research_summary:raw.research_summary||raw.overview||'',confidence:/^(high|medium|low)$/i.test(raw.confidence||'')?raw.confidence.toLowerCase():'medium',sources,images,use_disclaimer:'Effects and uses are commonly reported by consumers and public sources. They are not medical advice.',researched_at:new Date().toISOString()}}
async function run(name,hints){let e=await evidence(name,hints),sources=e.map(x=>({title:x.title,url:x.url,publisher:x.publisher||host(x.url),source_type:dm(x.publisher||host(x.url),TRUST)?'established cannabis source':'public cannabis source'})).slice(0,12),cands=uniq(e.flatMap(x=>x.images||[]),x=>x.image_url).map(x=>({...x,_s:iscore(x,name)})).filter(x=>x._s>=2).sort((a,b)=>b._s-a._s).slice(0,6),downs=(await Promise.all(cands.map(dl))).filter(Boolean),parts=[{text:prompt(name,hints,e,downs)}];downs.forEach((im,i)=>{parts.push({text:`Candidate image ${i+1}. Source: ${im.source_url}. Alt: ${im.alt||''}.`});parts.push({inlineData:{mimeType:im.mime,data:im.data}})});let g=await model(parts,5000,50000),raw=json(g.text),accepted=[];for(let r of Array.isArray(raw.image_results)?raw.image_results:[]){let im=downs[Number(r.index)-1],cl=String(r.classification||'').toLowerCase(),cf=Number(r.confidence||0);if(im&&['cannabis_flower','cannabis_live_plant'].includes(cl)&&cf>=.72)accepted.push({image_url:im.image_url,source_url:im.source_url,publisher:im.publisher,title:im.title,visual_type:cl,visual_confidence:cf})}return profile(raw,name,sources,accepted.slice(0,4))}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();let test=req.method==='GET'&&req.query?.test===TS;if(!test){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});if(!await user(req.headers.authorization))return res.status(401).json({error:'Sign in again and retry.'})}try{let b=test?req.query:(typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})),name=String(b.name||b.requested_name||'').trim(),h=String(b.hints||'').trim();if(!name)return res.status(400).json({error:'Enter a strain name.'});return res.status(200).json({ok:true,profile:await run(name,h)})}catch(e){console.error(e);return res.status(500).json({error:e.message||'Research failed.'})}};
